steps:
  # build container image
- name: "gcr.io/cloud-builders/docker"
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpflask','.']
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ['push','gcr.io/$PROJECT_ID/gcpflask','.']
  # deploy the container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args: 
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpflask
  - --location=us-central1-c
  - --clusters=gcp-devops
  - --namespace=gcp-devops-prod