apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: gcr.io/deep-voyage-384219/gcpflask:latest
        name: gcp-flask
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-app
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: flask-app-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-app
  sessionAffinity: None
  type: LoadBalancer


